== Macros

=== Las utilidades de macros abstraen...

[%step]
- La **generacion** de nuevo codigo
- El **filtrado** de codigo sobre el que quieres aplicar una transformacion
- La **transformacion** de codigo

=== Utilidades

- `macro {}` (generacion)
- `MacroClass {}` (generacion)
- `@Macro` (transformacion)
- `ASTMatcher` (filtrado)

=== macro method

[%step]
- Nos permite crear **statements** y **expressions**
- De manera mas facil y natural

=== macro method

[source, groovy]
.Este codigo
----
include::{macros-examples}/src/main/groovy/madridgug/macros/method/SafeCalls.groovy[indent=0]
----

[source, groovy]
.Deberia contemplar este test
----
include::{macros-examples}/src/test/groovy/madridgug/macros/method/SafeCallsSpec.groovy[tags=unsafe_calls,indent=0]
----

=== macro method

Como crear la guarda antes del codigo ?

[%step]
- API AST "A pelo"
- GeneralUtils para reducirlo
- macro {}

=== macro method

[source, groovy]
.API ASTs
----
include::{macros}/src/main/groovy/madridgug/macros/method/MakeParamSafeTransformation.groovy[tags=longer, indent=0]
----

[source, groovy]
.GeneralUtils
----
include::{macros}/src/main/groovy/madridgug/macros/method/MakeParamSafeTransformation.groovy[tags=shorter, indent=0]
----

=== macro method

[source, groovy]
.macro {}
----
include::{macros}/src/main/groovy/madridgug/macros/method/MakeParamSafeTransformation.groovy[tags=macro, indent=0]
----
<1> Las expressiones se interpolan
<2> Dentro de codigo plano

=== macro method

[source, groovy]
.Mejor caso de uso
----
include::{macros}/src/main/groovy/madridgug/macros/method/ToMD5Transformation.groovy[tags=longer_use_case, indent=0]
----

=== MacroClass

[%step]
- Para crear clases y/o metodos con la misma tecnica que con el `macro {}` method

=== MacroClass

[source, groovy]
.Creacion de clase
----
include::{macros}/src/main/groovy/madridgug/macros/method/StatisticsASTTransformation.groovy[tags=macroClass, indent=0]
----

=== MacroClass

[source, groovy]
.Creacion de clase
----
include::{macros-examples}/src/main/groovy/madridgug/macros/method/ProcessorWithStatistics.groovy[indent=0]
----

=== MacroClass

[source, groovy]
.Creacion de clase
----
include::{macros-examples}/src/test/groovy/madridgug/macros/method/ProcessorWithStatisticsSpec.groovy[tags=statistics, indent=0]
----
